---
- hosts: localhost

  tasks:
    - rds:
        aws_access_key: '{{aws_access_key}}'
        aws_secret_key: '{{aws_secret_key}}'
        region: '{{region}}'
        instance_name: '{{instancename}}'
        command: restore
        snapshot: '{{snapshot_name}}'
