---
- hosts: localhost

  tasks:
    - ec2:
        aws_access_key: '{{aws_access_key}}'
        aws_secret_key: '{{aws_secret_key}}'
        region: '{{region}}'
        instance_type: '{{instancetype}}'
        image: '{{image}}'
        wait: yes
        wait_timeout: 500
        count: 5
        instance_tags:
          Name: '{{instance_Name}}'
        volumes:
        - device_name: '{{device_name}}'
          snapshot: '{{snapshotid}}'
          volume_size: '{{volumesize}}'
        monitoring: yes
        vpc_subnet_id: '{{vpc_subnet_id}}'
        assign_public_ip: yes
