---
- hosts: localhost

  tasks:
    - rds:
        aws_access_key: '{{aws_access_key}}'
        aws_secret_key: '{{aws_secret_key}}'
        region: '{{region}}'
        command: reboot
        instance_name: '{{instance_name}}'
