---
- hosts: localhost

  tasks:
    - ec2_snapshot:
        aws_access_key: '{{aws_access_key}}'
        aws_secret_key: '{{aws_secret_key}}'
        region: '{{region}}'
        volume_id: '{{volumeid}}'
        snapshot_tags:
          frequency: hourly
          source: /data
      register: snapshot
    - debug: var=snapshot
